### ISSUE TITLE
[Edit profile info] UI problem and missing prompts.

### ISSUE THREAD

**Issue by Dagtwice** [AlexAgnoII/SOFENGG#50]
![4](https://user-images.githubusercontent.com/25523187/33941395-6fd8472c-e04d-11e7-9f1c-d8eb2c425f1a.gif)

Tested By: Dan
Date Tested:
12-13-2017
9:33 PM

Test Case Description:
Editing fields with an invalid input.

Steps to reproduce error:

- Address: Sample
- City: 1
- Province: 1
- Country: 1
- Zip Code: a
- Mobile Number: a
- Telephone Number:  a
- Birthday: 02/15/2000
- Gender: 1
- Civil Status: 1
- Nationality: 1

Expected Output:

- The user will not be allowed to edit the information.
- The user will be prompted of the required input.

Actual Output:

- The user wasn’t allowed to save the changes made.
- The user was prompted for the errors except the **gender, civil status, and nationality fields.**
- UI inconsistency throughout the system.

**Comment by Dagtwice** [comment]
I think it would be better if there would be just a "combo box" or dropdown menu for the gender and civil status to avoid invalid inputs. Or, just restrict the users from entering a "non-string" input for the gender and civil status.

**Comment by roiiigibiv** [comment]
- Fixed the UI for the pop-ups of constraints
- Added prompts for errors in gender, civil status and nationality fields 
Please re-evaluate. Thanks

**Comment by Dagtwice** [comment]
- Prompts were all good, but the contents of the form still gets misaligned.
![image](https://user-images.githubusercontent.com/25523187/33991159-7cb6da38-e108-11e7-9a03-76c8db75c665.png)


- Would it be possible to replicate the UI of the prompts of the login page into that? (Pic for reference)
![image](https://user-images.githubusercontent.com/25523187/33991211-b221d222-e108-11e7-8f99-94640855fb18.png)

**Comment by roiiigibiv** [comment]
UI of the prompts from login/signup page was replicated. Tried to keep the misalignment to minimal. Kindly please re-evaluate. Thank you.
